export const PROCESSES = {
  'lead-to-cash': {
    id: 'lead-to-cash',
    name: 'Lead to Cash',
    emoji: '💼',
    tagline: 'From first contact to closed deal — fully automated',
    timeEstimate: '8 minutes',
    exampleFinding:
      'Companies typically find 35–55% of Lead-to-Cash activities are still manual — representing 200+ hrs/week of avoidable work.',
    whatYouDiscover: [
      'Lead capture & qualification gaps',
      'CRM automation coverage (Salesforce, HubSpot)',
      'Contract & proposal generation efficiency',
      'Order management & fulfilment bottlenecks',
      'Invoice processing & revenue recognition',
    ],
    stages: [
      { id: 'l2c-1', name: 'Lead Capture & Qualification', description: 'Capturing inbound/outbound leads and qualifying them against ideal customer criteria before handoff to sales.' },
      { id: 'l2c-2', name: 'Opportunity Management', description: 'Managing the full sales cycle from qualified lead through pipeline stages to negotiation.' },
      { id: 'l2c-3', name: 'Proposal & Quoting', description: 'Generating accurate quotes and proposals, managing pricing approvals, and delivering to prospects.' },
      { id: 'l2c-4', name: 'Contract & Legal', description: 'Drafting, reviewing, redlining, approving, and executing customer contracts and NDAs.' },
      { id: 'l2c-5', name: 'Order Management', description: 'Processing confirmed orders, managing inventory availability, fulfilment orchestration, and shipping.' },
      { id: 'l2c-6', name: 'Invoice & Billing', description: 'Generating invoices, handling billing disputes, managing recurring billing cycles and revenue recognition.' },
      { id: 'l2c-7', name: 'Collections & Cash Application', description: 'Following up on overdue invoices, applying cash receipts, and reconciling accounts receivable.' },
    ],
  },
  'procure-to-pay': {
    id: 'procure-to-pay',
    name: 'Procure to Pay',
    emoji: '🛒',
    tagline: 'From requisition to supplier payment — fully automated',
    timeEstimate: '8 minutes',
    exampleFinding: 'P2P teams typically recover 30+ hrs/week by automating PO matching and invoice processing.',
    whatYouDiscover: ['Requisition and approval gaps', 'Vendor onboarding automation', 'PO matching efficiency', 'Invoice processing', 'Payment scheduling'],
    stages: [
      { id: 'p2p-1', name: 'Requisition & Approval', description: 'Creating purchase requests, routing for approval, budget validation and commitment.' },
      { id: 'p2p-2', name: 'Supplier Selection & PO', description: 'RFQ/RFP management, supplier evaluation, purchase order creation and dispatch.' },
      { id: 'p2p-3', name: 'Goods Receipt', description: 'Receiving goods and services, inspection, GR/IR matching against purchase orders.' },
      { id: 'p2p-4', name: 'Invoice Processing', description: 'Invoice capture, 3-way matching (PO/GR/invoice), discrepancy resolution.' },
      { id: 'p2p-5', name: 'Payment Execution', description: 'Payment scheduling, approval, bank file generation, cash flow management.' },
      { id: 'p2p-6', name: 'Supplier Reconciliation', description: 'Statement reconciliation, dispute management, vendor master maintenance.' },
    ],
  },
  'order-to-cash': {
    id: 'order-to-cash',
    name: 'Order to Cash',
    emoji: '📦',
    tagline: 'From customer order to revenue recognition — seamless',
    timeEstimate: '8 minutes',
    exampleFinding: 'O2C teams recover 40+ hrs/week by automating order validation, fulfilment and cash application.',
    whatYouDiscover: ['Order management gaps', 'Fulfilment automation', 'Invoicing efficiency', 'Collections processes', 'Revenue recognition'],
    stages: [
      { id: 'o2c-1', name: 'Order Management', description: 'Order receipt, validation, credit check, order confirmation and acknowledgement.' },
      { id: 'o2c-2', name: 'Fulfilment & Shipping', description: 'Inventory allocation, pick/pack/ship, carrier selection, tracking and proof of delivery.' },
      { id: 'o2c-3', name: 'Invoicing & Billing', description: 'Invoice generation, delivery, billing disputes, recurring billing management.' },
      { id: 'o2c-4', name: 'Cash Application', description: 'Payment receipt, matching to invoices, exception handling, unapplied cash.' },
      { id: 'o2c-5', name: 'Collections', description: 'Aging analysis, dunning workflows, dispute resolution, write-off management.' },
      { id: 'o2c-6', name: 'Revenue Recognition', description: 'ASC 606/IFRS 15 compliance, deferred revenue, period-end recognition schedules.' },
    ],
  },
  'record-to-report': {
    id: 'record-to-report',
    name: 'Record to Report',
    emoji: '📊',
    tagline: 'From transaction capture to financial close — accelerated',
    timeEstimate: '8 minutes',
    exampleFinding: 'Finance teams cut close cycles by 40% by automating journal entries, reconciliations and reporting.',
    whatYouDiscover: ['Journal entry automation', 'Reconciliation efficiency', 'Close management', 'Financial reporting', 'Compliance readiness'],
    stages: [
      { id: 'r2r-1', name: 'Transaction Recording', description: 'Automated journal entries, sub-ledger postings, intercompany eliminations.' },
      { id: 'r2r-2', name: 'Account Reconciliation', description: 'Balance sheet reconciliations, bank reconciliations, variance investigation.' },
      { id: 'r2r-3', name: 'Period-End Close', description: 'Close checklist management, accruals, prepayments, depreciation runs.' },
      { id: 'r2r-4', name: 'Consolidation', description: 'Legal entity consolidation, FX translation, intercompany elimination, GAAP adjustments.' },
      { id: 'r2r-5', name: 'Financial Reporting', description: 'P&L, balance sheet, cash flow statements, management reporting packages.' },
      { id: 'r2r-6', name: 'Analysis & Compliance', description: 'Compliance trail maintenance, SOX controls, regulatory filings, statutory reporting.' },
    ],
  },
  'issue-to-resolution': {
    id: 'issue-to-resolution',
    name: 'Issue to Resolution',
    emoji: '🔧',
    tagline: 'From incident detection to customer satisfaction — automated',
    timeEstimate: '8 minutes',
    exampleFinding: 'Service teams reduce MTTR by 60% by automating triage, routing and resolution workflows.',
    whatYouDiscover: ['Incident detection gaps', 'Triage automation', 'Escalation workflows', 'Resolution efficiency', 'Knowledge management'],
    stages: [
      { id: 'i2r-1', name: 'Issue Detection & Logging', description: 'Multi-channel issue intake, auto-classification, deduplication, ticket creation.' },
      { id: 'i2r-2', name: 'Triage & Prioritisation', description: 'Severity scoring, SLA assignment, initial diagnosis, priority routing.' },
      { id: 'i2r-3', name: 'Assignment & Investigation', description: 'Skill-based routing, workload balancing, diagnostic tools, root cause analysis.' },
      { id: 'i2r-4', name: 'Resolution & Fix', description: 'Solution implementation, change management, knowledge base updates, fix validation.' },
      { id: 'i2r-5', name: 'Communication & Closure', description: 'Customer updates, resolution confirmation, satisfaction survey, ticket closure.' },
      { id: 'i2r-6', name: 'Post-Incident Review', description: 'RCA documentation, problem management, recurring issue prevention, SLA reporting.' },
    ],
  },
  'hire-to-retire': {
    id: 'hire-to-retire',
    name: 'Hire to Retire',
    emoji: '👥',
    tagline: 'From sourcing talent to seamless offboarding — AI-powered',
    timeEstimate: '8 minutes',
    exampleFinding:
      'HR teams typically recover 40+ hrs/week by automating onboarding, payroll processing, and compliance reporting alone.',
    whatYouDiscover: [
      'Recruitment & applicant tracking gaps',
      'Onboarding workflow automation',
      'Performance management processes',
      'Payroll & benefits processing',
      'Offboarding compliance & data handling',
    ],
    stages: [
      { id: 'h2r-1', name: 'Recruitment & Talent Acquisition', description: 'Job requisition approval, job posting, applicant tracking, screening, interviewing, and offer management.' },
      { id: 'h2r-2', name: 'Onboarding', description: 'Pre-hire documentation, IT provisioning, orientation scheduling, training assignments, and compliance sign-offs.' },
      { id: 'h2r-3', name: 'Performance Management', description: 'Goal setting, continuous feedback, mid-year and annual review cycles, and performance improvement plans.' },
      { id: 'h2r-4', name: 'Learning & Development', description: 'Training needs analysis, course enrolment, LMS management, certification tracking, and skills gap analysis.' },
      { id: 'h2r-5', name: 'Compensation & Benefits', description: 'Salary benchmarking, merit review cycles, benefits enrolment, changes management, and total rewards statements.' },
      { id: 'h2r-6', name: 'Payroll Processing', description: 'Payroll calculation, tax withholding, deductions management, payslip generation, and statutory reporting.' },
      { id: 'h2r-7', name: 'Offboarding & Compliance', description: 'Exit interviews, asset retrieval, system access revocation, final payroll processing, and data retention compliance.' },
    ],
  },
};

export const TECH_CATEGORIES = [
  {
    id: 'crm',
    label: 'CRM',
    icon: '🤝',
    options: ['Salesforce', 'HubSpot', 'Microsoft Dynamics CRM', 'Zoho CRM', 'Oracle CX', 'None'],
  },
  {
    id: 'erp',
    label: 'ERP',
    icon: '⚙️',
    options: ['SAP S/4HANA', 'SAP ECC', 'Oracle ERP Cloud', 'Microsoft Dynamics 365 F&O', 'NetSuite', 'None'],
  },
  {
    id: 'integration',
    label: 'Integration',
    icon: '🔗',
    options: ['Boomi', 'MuleSoft', 'Azure Integration Services', 'Informatica', 'Workato', 'None'],
  },
  {
    id: 'data',
    label: 'Data & Analytics',
    icon: '📊',
    options: ['Snowflake', 'Databricks', 'Microsoft Fabric', 'Power BI', 'Tableau', 'None'],
  },
  {
    id: 'hrms',
    label: 'HRMS',
    icon: '👤',
    options: ['Workday', 'SAP SuccessFactors', 'ADP', 'BambooHR', 'UKG', 'None'],
  },
];
