export const TOOL_CATEGORIES = [
  {
    id: 'crm',
    label: 'CRM',
    description: 'Customer relationship & sales platforms',
    tools: [
      { id: 'salesforce',  name: 'Salesforce',       logo: 'SF' },
      { id: 'hubspot',     name: 'HubSpot',           logo: 'HS' },
      { id: 'd365-sales',  name: 'Dynamics 365',      logo: 'D3' },
      { id: 'zoho-crm',    name: 'Zoho CRM',          logo: 'ZO' },
      { id: 'oracle-cx',   name: 'Oracle CX',         logo: 'OC' },
      { id: 'pipedrive',   name: 'Pipedrive',         logo: 'PD' },
    ],
  },
  {
    id: 'erp',
    label: 'ERP',
    description: 'Enterprise resource planning systems',
    tools: [
      { id: 'sap-s4',      name: 'SAP S/4HANA',       logo: 'S4' },
      { id: 'sap-ecc',     name: 'SAP ECC',           logo: 'SE' },
      { id: 'oracle-erp',  name: 'Oracle ERP',        logo: 'OR' },
      { id: 'd365-fo',     name: 'D365 F&O',          logo: 'FO' },
      { id: 'netsuite',    name: 'NetSuite',           logo: 'NS' },
      { id: 'sage',        name: 'Sage',               logo: 'SG' },
    ],
  },
  {
    id: 'hr',
    label: 'HR',
    description: 'Human capital management platforms',
    tools: [
      { id: 'workday',     name: 'Workday',            logo: 'WD' },
      { id: 'sap-sf',      name: 'SAP SuccessFactors', logo: 'SS' },
      { id: 'adp',         name: 'ADP',                logo: 'AP' },
      { id: 'bamboo',      name: 'BambooHR',           logo: 'BH' },
      { id: 'ukg',         name: 'UKG',                logo: 'UK' },
      { id: 'ceridian',    name: 'Ceridian',           logo: 'CD' },
    ],
  },
  {
    id: 'marketing',
    label: 'Marketing',
    description: 'Marketing automation & campaign tools',
    tools: [
      { id: 'marketo',     name: 'Marketo',            logo: 'MK' },
      { id: 'pardot',      name: 'Pardot',             logo: 'PA' },
      { id: 'eloqua',      name: 'Eloqua',             logo: 'EL' },
      { id: 'hubspot-mkt', name: 'HubSpot Mkt',        logo: 'HM' },
      { id: 'mailchimp',   name: 'Mailchimp',          logo: 'MC' },
      { id: 'adobe-mkt',   name: 'Adobe Marketo',      logo: 'AM' },
    ],
  },
  {
    id: 'integration',
    label: 'Integration',
    description: 'iPaaS & middleware platforms',
    tools: [
      { id: 'boomi',       name: 'Boomi',              logo: 'BO' },
      { id: 'mulesoft',    name: 'MuleSoft',           logo: 'MS' },
      { id: 'azure-int',   name: 'Azure Integ.',       logo: 'AI' },
      { id: 'informatica', name: 'Informatica',        logo: 'IN' },
      { id: 'workato',     name: 'Workato',            logo: 'WK' },
      { id: 'snaplogic',   name: 'SnapLogic',          logo: 'SL' },
    ],
  },
  {
    id: 'itsm',
    label: 'ITSM',
    description: 'IT service management & ticketing',
    tools: [
      { id: 'servicenow',  name: 'ServiceNow',         logo: 'SN' },
      { id: 'jira-sm',     name: 'Jira Svc Mgmt',      logo: 'JS' },
      { id: 'freshservice',name: 'Freshservice',       logo: 'FS' },
      { id: 'zendesk',     name: 'Zendesk',            logo: 'ZD' },
      { id: 'bmc-remedy',  name: 'BMC Remedy',         logo: 'BR' },
      { id: 'ivanti',      name: 'Ivanti',             logo: 'IV' },
    ],
  },
];
